name: thebibleshop
favicon: null
layout_spectrum: 0.50196
typography_spectrum: 0.74853
title: The Bible Shop
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f3efe3'
    - '#ba7d47'
    - '#ab2b00'
    - '#01653c'
  brandStrength: 1
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
