name: thebibleshop
favicon: null
layout_spectrum: 0.50196
typography_spectrum: 0.50196
title: The Bible Shop
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f3efe3'
    - '#ba7d47'
    - '#ab2b00'
    - '#01653c'
  brandStrength: 0.0282300494145602
  lightness: 0.8322242242284119
  saturation: 0.060777013655751944
  rhythmicContrast: 0.7874509943649173
purpose: []
